# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alphablending.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_alphablending(object):
    def setupUi(self, Dialog_alphablending):
        Dialog_alphablending.setObjectName("Dialog_alphablending")
        Dialog_alphablending.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_alphablending.sizePolicy().hasHeightForWidth())
        Dialog_alphablending.setSizePolicy(sizePolicy)
        Dialog_alphablending.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_alphablending.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_alphablending)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_alphablending)
        self.widget.setGeometry(QtCore.QRect(64, 30, 79, 25))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_alpha = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_alpha.setMaximum(1.0)
        self.doubleSpinBox_alpha.setSingleStep(0.01)
        self.doubleSpinBox_alpha.setProperty("value", 0.5)
        self.doubleSpinBox_alpha.setObjectName("doubleSpinBox_alpha")
        self.gridLayout.addWidget(self.doubleSpinBox_alpha, 0, 1, 1, 1)

        self.retranslateUi(Dialog_alphablending)
        self.buttonBox.accepted.connect(Dialog_alphablending.accept)
        self.buttonBox.rejected.connect(Dialog_alphablending.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_alphablending)

    def retranslateUi(self, Dialog_alphablending):
        _translate = QtCore.QCoreApplication.translate
        Dialog_alphablending.setWindowTitle(_translate("Dialog_alphablending", "Alpha Blending"))
        self.label.setText(_translate("Dialog_alphablending", "Alpha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_alphablending = QtWidgets.QDialog()
    ui = Ui_Dialog_alphablending()
    ui.setupUi(Dialog_alphablending)
    Dialog_alphablending.show()
    sys.exit(app.exec_())
