# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blur_average.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_avgblur(object):
    def setupUi(self, Dialog_avgblur):
        Dialog_avgblur.setObjectName("Dialog_avgblur")
        Dialog_avgblur.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_avgblur.sizePolicy().hasHeightForWidth())
        Dialog_avgblur.setSizePolicy(sizePolicy)
        Dialog_avgblur.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_avgblur.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_avgblur)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_avgblur)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 180, 55))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_kernelsize = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_kernelsize.setMinimum(1)
        self.spinBox_kernelsize.setObjectName("spinBox_kernelsize")
        self.gridLayout.addWidget(self.spinBox_kernelsize, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_numberofapplications = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_numberofapplications.setObjectName("spinBox_numberofapplications")
        self.gridLayout.addWidget(self.spinBox_numberofapplications, 1, 1, 1, 1)

        self.retranslateUi(Dialog_avgblur)
        self.buttonBox.accepted.connect(Dialog_avgblur.accept)
        self.buttonBox.rejected.connect(Dialog_avgblur.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_avgblur)

    def retranslateUi(self, Dialog_avgblur):
        _translate = QtCore.QCoreApplication.translate
        Dialog_avgblur.setWindowTitle(_translate("Dialog_avgblur", "Average Blur"))
        self.label.setText(_translate("Dialog_avgblur", "Kernel Size"))
        self.label_2.setText(_translate("Dialog_avgblur", "Number of applications"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_avgblur = QtWidgets.QDialog()
    ui = Ui_Dialog_avgblur()
    ui.setupUi(Dialog_avgblur)
    Dialog_avgblur.show()
    sys.exit(app.exec_())
