# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartoonify.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_cartoonify(object):
    def setupUi(self, Dialog_cartoonify):
        Dialog_cartoonify.setObjectName("Dialog_cartoonify")
        Dialog_cartoonify.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_cartoonify.sizePolicy().hasHeightForWidth())
        Dialog_cartoonify.setSizePolicy(sizePolicy)
        Dialog_cartoonify.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_cartoonify.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_cartoonify)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_cartoonify)
        self.widget.setGeometry(QtCore.QRect(100, 20, 113, 55))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_thresh1 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_thresh1.setMaximum(255)
        self.spinBox_thresh1.setSingleStep(10)
        self.spinBox_thresh1.setObjectName("spinBox_thresh1")
        self.gridLayout.addWidget(self.spinBox_thresh1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_thresh2 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_thresh2.setMaximum(255)
        self.spinBox_thresh2.setSingleStep(10)
        self.spinBox_thresh2.setObjectName("spinBox_thresh2")
        self.gridLayout.addWidget(self.spinBox_thresh2, 1, 1, 1, 1)

        self.retranslateUi(Dialog_cartoonify)
        self.buttonBox.accepted.connect(Dialog_cartoonify.accept)
        self.buttonBox.rejected.connect(Dialog_cartoonify.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_cartoonify)

    def retranslateUi(self, Dialog_cartoonify):
        _translate = QtCore.QCoreApplication.translate
        Dialog_cartoonify.setWindowTitle(_translate("Dialog_cartoonify", "Cartoonify"))
        self.label.setText(_translate("Dialog_cartoonify", "Threshold 1"))
        self.label_2.setText(_translate("Dialog_cartoonify", "Threshold 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_cartoonify = QtWidgets.QDialog()
    ui = Ui_Dialog_cartoonify()
    ui.setupUi(Dialog_cartoonify)
    Dialog_cartoonify.show()
    sys.exit(app.exec_())
