# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dither.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_dither(object):
    def setupUi(self, Dialog_dither):
        Dialog_dither.setObjectName("Dialog_dither")
        Dialog_dither.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_dither.sizePolicy().hasHeightForWidth())
        Dialog_dither.setSizePolicy(sizePolicy)
        Dialog_dither.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_dither.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_dither)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_dither)
        self.widget.setGeometry(QtCore.QRect(130, 40, 67, 25))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_order = QtWidgets.QSpinBox(self.widget)
        self.spinBox_order.setObjectName("spinBox_order")
        self.gridLayout.addWidget(self.spinBox_order, 0, 1, 1, 1)

        self.retranslateUi(Dialog_dither)
        self.buttonBox.accepted.connect(Dialog_dither.accept)
        self.buttonBox.rejected.connect(Dialog_dither.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_dither)

    def retranslateUi(self, Dialog_dither):
        _translate = QtCore.QCoreApplication.translate
        Dialog_dither.setWindowTitle(_translate("Dialog_dither", "Enter Order"))
        self.label.setText(_translate("Dialog_dither", "Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_dither = QtWidgets.QDialog()
    ui = Ui_Dialog_dither()
    ui.setupUi(Dialog_dither)
    Dialog_dither.show()
    sys.exit(app.exec_())
