# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extractcolor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_extractcolor(object):
    def setupUi(self, Dialog_extractcolor):
        Dialog_extractcolor.setObjectName("Dialog_extractcolor")
        Dialog_extractcolor.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_extractcolor.sizePolicy().hasHeightForWidth())
        Dialog_extractcolor.setSizePolicy(sizePolicy)
        Dialog_extractcolor.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_extractcolor.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_extractcolor)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_extractcolor)
        self.widget.setGeometry(QtCore.QRect(70, 30, 149, 25))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_extractcolor = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_extractcolor.setObjectName("lineEdit_extractcolor")
        self.gridLayout.addWidget(self.lineEdit_extractcolor, 0, 1, 1, 1)

        self.retranslateUi(Dialog_extractcolor)
        self.buttonBox.accepted.connect(Dialog_extractcolor.accept)
        self.buttonBox.rejected.connect(Dialog_extractcolor.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_extractcolor)

    def retranslateUi(self, Dialog_extractcolor):
        _translate = QtCore.QCoreApplication.translate
        Dialog_extractcolor.setWindowTitle(_translate("Dialog_extractcolor", "Extract Color"))
        self.label.setText(_translate("Dialog_extractcolor", "Color"))
        self.lineEdit_extractcolor.setText(_translate("Dialog_extractcolor", "127, 127, 127"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_extractcolor = QtWidgets.QDialog()
    ui = Ui_Dialog_extractcolor()
    ui.setupUi(Dialog_extractcolor)
    Dialog_extractcolor.show()
    sys.exit(app.exec_())
