# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heatmap.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_heatmap(object):
    def setupUi(self, Dialog_heatmap):
        Dialog_heatmap.setObjectName("Dialog_heatmap")
        Dialog_heatmap.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_heatmap.sizePolicy().hasHeightForWidth())
        Dialog_heatmap.setSizePolicy(sizePolicy)
        Dialog_heatmap.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_heatmap.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_heatmap)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_heatmap)
        self.widget.setGeometry(QtCore.QRect(60, 30, 122, 21))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_heatmap = QtWidgets.QComboBox(self.widget)
        self.comboBox_heatmap.setObjectName("comboBox_heatmap")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.comboBox_heatmap.addItem("")
        self.gridLayout.addWidget(self.comboBox_heatmap, 0, 1, 1, 1)

        self.retranslateUi(Dialog_heatmap)
        self.buttonBox.accepted.connect(Dialog_heatmap.accept)
        self.buttonBox.rejected.connect(Dialog_heatmap.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_heatmap)

    def retranslateUi(self, Dialog_heatmap):
        _translate = QtCore.QCoreApplication.translate
        Dialog_heatmap.setWindowTitle(_translate("Dialog_heatmap", "Choose Map"))
        self.label.setText(_translate("Dialog_heatmap", "Map"))
        self.comboBox_heatmap.setItemText(0, _translate("Dialog_heatmap", "Autumn"))
        self.comboBox_heatmap.setItemText(1, _translate("Dialog_heatmap", "Bone"))
        self.comboBox_heatmap.setItemText(2, _translate("Dialog_heatmap", "Jet"))
        self.comboBox_heatmap.setItemText(3, _translate("Dialog_heatmap", "Winter"))
        self.comboBox_heatmap.setItemText(4, _translate("Dialog_heatmap", "Rainbow"))
        self.comboBox_heatmap.setItemText(5, _translate("Dialog_heatmap", "Ocean"))
        self.comboBox_heatmap.setItemText(6, _translate("Dialog_heatmap", "Summer"))
        self.comboBox_heatmap.setItemText(7, _translate("Dialog_heatmap", "Spring"))
        self.comboBox_heatmap.setItemText(8, _translate("Dialog_heatmap", "Cool"))
        self.comboBox_heatmap.setItemText(9, _translate("Dialog_heatmap", "HSV"))
        self.comboBox_heatmap.setItemText(10, _translate("Dialog_heatmap", "Pink"))
        self.comboBox_heatmap.setItemText(11, _translate("Dialog_heatmap", "Hot"))
        self.comboBox_heatmap.setItemText(12, _translate("Dialog_heatmap", "Parula"))
        self.comboBox_heatmap.setItemText(13, _translate("Dialog_heatmap", "Magma"))
        self.comboBox_heatmap.setItemText(14, _translate("Dialog_heatmap", "Inferno"))
        self.comboBox_heatmap.setItemText(15, _translate("Dialog_heatmap", "Plasma"))
        self.comboBox_heatmap.setItemText(16, _translate("Dialog_heatmap", "Viridis"))
        self.comboBox_heatmap.setItemText(17, _translate("Dialog_heatmap", "Cividis"))
        self.comboBox_heatmap.setItemText(18, _translate("Dialog_heatmap", "Twilight"))
        self.comboBox_heatmap.setItemText(19, _translate("Dialog_heatmap", "Twilight Shifted"))
        self.comboBox_heatmap.setItemText(20, _translate("Dialog_heatmap", "Turbo"))
        self.comboBox_heatmap.setItemText(21, _translate("Dialog_heatmap", "DeepGreen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_heatmap = QtWidgets.QDialog()
    ui = Ui_Dialog_heatmap()
    ui.setupUi(Dialog_heatmap)
    Dialog_heatmap.show()
    sys.exit(app.exec_())
