# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pixelate.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_pixelate(object):
    def setupUi(self, Dialog_pixelate):
        Dialog_pixelate.setObjectName("Dialog_pixelate")
        Dialog_pixelate.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_pixelate.sizePolicy().hasHeightForWidth())
        Dialog_pixelate.setSizePolicy(sizePolicy)
        Dialog_pixelate.setMinimumSize(QtCore.QSize(400, 100))
        Dialog_pixelate.setMaximumSize(QtCore.QSize(400, 100))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_pixelate)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_pixelate)
        self.widget.setGeometry(QtCore.QRect(110, 30, 87, 25))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_pixelate = QtWidgets.QSpinBox(self.widget)
        self.spinBox_pixelate.setObjectName("spinBox_pixelate")
        self.gridLayout.addWidget(self.spinBox_pixelate, 0, 1, 1, 1)

        self.retranslateUi(Dialog_pixelate)
        self.buttonBox.accepted.connect(Dialog_pixelate.accept)
        self.buttonBox.rejected.connect(Dialog_pixelate.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_pixelate)

    def retranslateUi(self, Dialog_pixelate):
        _translate = QtCore.QCoreApplication.translate
        Dialog_pixelate.setWindowTitle(_translate("Dialog_pixelate", "Enter Magnitude"))
        self.label.setText(_translate("Dialog_pixelate", "Magnitude"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_pixelate = QtWidgets.QDialog()
    ui = Ui_Dialog_pixelate()
    ui.setupUi(Dialog_pixelate)
    Dialog_pixelate.show()
    sys.exit(app.exec_())
