# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyramidblending_modified.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 291, 41))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(51, 81, 290, 113))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_image0 = QtWidgets.QComboBox(self.widget)
        self.comboBox_image0.setObjectName("comboBox_image0")
        self.comboBox_image0.addItem("")
        self.comboBox_image0.addItem("")
        self.comboBox_image0.addItem("")
        self.gridLayout.addWidget(self.comboBox_image0, 0, 0, 1, 1)
        self.label_image0 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image0.sizePolicy().hasHeightForWidth())
        self.label_image0.setSizePolicy(sizePolicy)
        self.label_image0.setMinimumSize(QtCore.QSize(211, 0))
        self.label_image0.setObjectName("label_image0")
        self.gridLayout.addWidget(self.label_image0, 0, 1, 1, 1)
        self.comboBox_image1 = QtWidgets.QComboBox(self.widget)
        self.comboBox_image1.setObjectName("comboBox_image1")
        self.comboBox_image1.addItem("")
        self.comboBox_image1.addItem("")
        self.comboBox_image1.addItem("")
        self.gridLayout.addWidget(self.comboBox_image1, 1, 0, 1, 1)
        self.label_image1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image1.sizePolicy().hasHeightForWidth())
        self.label_image1.setSizePolicy(sizePolicy)
        self.label_image1.setMinimumSize(QtCore.QSize(211, 0))
        self.label_image1.setObjectName("label_image1")
        self.gridLayout.addWidget(self.label_image1, 1, 1, 1, 1)
        self.comboBox_image2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_image2.setObjectName("comboBox_image2")
        self.comboBox_image2.addItem("")
        self.comboBox_image2.addItem("")
        self.comboBox_image2.addItem("")
        self.gridLayout.addWidget(self.comboBox_image2, 2, 0, 1, 1)
        self.label_image2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image2.sizePolicy().hasHeightForWidth())
        self.label_image2.setSizePolicy(sizePolicy)
        self.label_image2.setMinimumSize(QtCore.QSize(211, 0))
        self.label_image2.setObjectName("label_image2")
        self.gridLayout.addWidget(self.label_image2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox_levels = QtWidgets.QSpinBox(self.widget)
        self.spinBox_levels.setObjectName("spinBox_levels")
        self.gridLayout.addWidget(self.spinBox_levels, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pyramid Blending"))
        self.label.setText(_translate("Dialog", "Please choose top, bottom and mask images and \n"
"levels of pyramids"))
        self.comboBox_image0.setItemText(0, _translate("Dialog", "Top"))
        self.comboBox_image0.setItemText(1, _translate("Dialog", "Bottom"))
        self.comboBox_image0.setItemText(2, _translate("Dialog", "Mask"))
        self.label_image0.setText(_translate("Dialog", "image0"))
        self.comboBox_image1.setItemText(0, _translate("Dialog", "Top"))
        self.comboBox_image1.setItemText(1, _translate("Dialog", "Bottom"))
        self.comboBox_image1.setItemText(2, _translate("Dialog", "Mask"))
        self.label_image1.setText(_translate("Dialog", "image1"))
        self.comboBox_image2.setItemText(0, _translate("Dialog", "Top"))
        self.comboBox_image2.setItemText(1, _translate("Dialog", "Bottom"))
        self.comboBox_image2.setItemText(2, _translate("Dialog", "Mask"))
        self.label_image2.setText(_translate("Dialog", "image2"))
        self.label_4.setText(_translate("Dialog", "Levels"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
