# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyramidblending.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 21, 371, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_image1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_image1.setObjectName("lineEdit_image1")
        self.gridLayout.addWidget(self.lineEdit_image1, 0, 1, 1, 1)
        self.pushButton_browse_image1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_browse_image1.setObjectName("pushButton_browse_image1")
        self.gridLayout.addWidget(self.pushButton_browse_image1, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_image2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_image2.setObjectName("lineEdit_image2")
        self.gridLayout.addWidget(self.lineEdit_image2, 1, 1, 1, 1)
        self.pushButton_browse_image2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_browse_image2.setObjectName("pushButton_browse_image2")
        self.gridLayout.addWidget(self.pushButton_browse_image2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.gridLayout.addWidget(self.lineEdit_mask, 2, 1, 1, 1)
        self.pushButton_browse_mask = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_browse_mask.setObjectName("pushButton_browse_mask")
        self.gridLayout.addWidget(self.pushButton_browse_mask, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox_levels = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_levels.setObjectName("spinBox_levels")
        self.gridLayout.addWidget(self.spinBox_levels, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Load Files"))
        self.label.setText(_translate("Dialog", "Image 1"))
        self.pushButton_browse_image1.setText(_translate("Dialog", "Browse"))
        self.label_2.setText(_translate("Dialog", "Image 2"))
        self.pushButton_browse_image2.setText(_translate("Dialog", "Browse"))
        self.label_3.setText(_translate("Dialog", "Mask"))
        self.pushButton_browse_mask.setText(_translate("Dialog", "Browse"))
        self.label_4.setText(_translate("Dialog", "Levels"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
