# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_color.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_replacecolor(object):
    def setupUi(self, Dialog_replacecolor):
        Dialog_replacecolor.setObjectName("Dialog_replacecolor")
        Dialog_replacecolor.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_replacecolor.sizePolicy().hasHeightForWidth())
        Dialog_replacecolor.setSizePolicy(sizePolicy)
        Dialog_replacecolor.setMinimumSize(QtCore.QSize(400, 200))
        Dialog_replacecolor.setMaximumSize(QtCore.QSize(400, 200))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_replacecolor)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_replacecolor)
        self.widget.setGeometry(QtCore.QRect(21, 21, 240, 161))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.radioButton_greater = QtWidgets.QRadioButton(self.widget)
        self.radioButton_greater.setObjectName("radioButton_greater")
        self.gridLayout.addWidget(self.radioButton_greater, 3, 1, 1, 1)
        self.radioButton_equal = QtWidgets.QRadioButton(self.widget)
        self.radioButton_equal.setChecked(True)
        self.radioButton_equal.setObjectName("radioButton_equal")
        self.gridLayout.addWidget(self.radioButton_equal, 4, 1, 1, 1)
        self.radioButton_lesser = QtWidgets.QRadioButton(self.widget)
        self.radioButton_lesser.setObjectName("radioButton_lesser")
        self.gridLayout.addWidget(self.radioButton_lesser, 5, 1, 1, 1)

        self.retranslateUi(Dialog_replacecolor)
        self.buttonBox.accepted.connect(Dialog_replacecolor.accept)
        self.buttonBox.rejected.connect(Dialog_replacecolor.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_replacecolor)

    def retranslateUi(self, Dialog_replacecolor):
        _translate = QtCore.QCoreApplication.translate
        Dialog_replacecolor.setWindowTitle(_translate("Dialog_replacecolor", "Replace Color"))
        self.label.setText(_translate("Dialog_replacecolor", "Color to Replace"))
        self.lineEdit.setText(_translate("Dialog_replacecolor", "255, 255, 255"))
        self.label_2.setText(_translate("Dialog_replacecolor", "Target Color"))
        self.lineEdit_2.setText(_translate("Dialog_replacecolor", "255, 255, 0"))
        self.label_3.setText(_translate("Dialog_replacecolor", "Choose operator:"))
        self.radioButton_greater.setText(_translate("Dialog_replacecolor", "Greater"))
        self.radioButton_equal.setText(_translate("Dialog_replacecolor", "Equal"))
        self.radioButton_lesser.setText(_translate("Dialog_replacecolor", "Less"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_replacecolor = QtWidgets.QDialog()
    ui = Ui_Dialog_replacecolor()
    ui.setupUi(Dialog_replacecolor)
    Dialog_replacecolor.show()
    sys.exit(app.exec_())
