# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resize_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_resize(object):
    def setupUi(self, Dialog_resize):
        Dialog_resize.setObjectName("Dialog_resize")
        Dialog_resize.resize(391, 132)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_resize)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_resize)
        self.widget.setGeometry(QtCore.QRect(33, 21, 169, 57))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_width = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_width.setSingleStep(0.01)
        self.doubleSpinBox_width.setProperty("value", 1.0)
        self.doubleSpinBox_width.setObjectName("doubleSpinBox_width")
        self.gridLayout.addWidget(self.doubleSpinBox_width, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox_height = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_height.setSingleStep(0.01)
        self.doubleSpinBox_height.setProperty("value", 1.0)
        self.doubleSpinBox_height.setObjectName("doubleSpinBox_height")
        self.gridLayout.addWidget(self.doubleSpinBox_height, 1, 1, 1, 1)

        self.retranslateUi(Dialog_resize)
        self.buttonBox.accepted.connect(Dialog_resize.accept)
        self.buttonBox.rejected.connect(Dialog_resize.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_resize)

    def retranslateUi(self, Dialog_resize):
        _translate = QtCore.QCoreApplication.translate
        Dialog_resize.setWindowTitle(_translate("Dialog_resize", "Resize"))
        self.label.setText(_translate("Dialog_resize", "Width - multiplier"))
        self.label_2.setText(_translate("Dialog_resize", "Height - multiplier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_resize = QtWidgets.QDialog()
    ui = Ui_Dialog_resize()
    ui.setupUi(Dialog_resize)
    Dialog_resize.show()
    sys.exit(app.exec_())
