# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verticalnoisebands.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_noiseband_vertical(object):
    def setupUi(self, Dialog_noiseband_vertical):
        Dialog_noiseband_vertical.setObjectName("Dialog_noiseband_vertical")
        Dialog_noiseband_vertical.resize(400, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_noiseband_vertical.sizePolicy().hasHeightForWidth())
        Dialog_noiseband_vertical.setSizePolicy(sizePolicy)
        Dialog_noiseband_vertical.setMinimumSize(QtCore.QSize(400, 120))
        Dialog_noiseband_vertical.setMaximumSize(QtCore.QSize(400, 120))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_noiseband_vertical)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_noiseband_vertical)
        self.widget.setGeometry(QtCore.QRect(100, 21, 103, 85))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_width = QtWidgets.QSpinBox(self.widget)
        self.spinBox_width.setSingleStep(10)
        self.spinBox_width.setObjectName("spinBox_width")
        self.gridLayout.addWidget(self.spinBox_width, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_period = QtWidgets.QSpinBox(self.widget)
        self.spinBox_period.setSingleStep(10)
        self.spinBox_period.setObjectName("spinBox_period")
        self.gridLayout.addWidget(self.spinBox_period, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_magnitude = QtWidgets.QSpinBox(self.widget)
        self.spinBox_magnitude.setSingleStep(10)
        self.spinBox_magnitude.setObjectName("spinBox_magnitude")
        self.gridLayout.addWidget(self.spinBox_magnitude, 2, 1, 1, 1)

        self.retranslateUi(Dialog_noiseband_vertical)
        self.buttonBox.accepted.connect(Dialog_noiseband_vertical.accept)
        self.buttonBox.rejected.connect(Dialog_noiseband_vertical.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_noiseband_vertical)

    def retranslateUi(self, Dialog_noiseband_vertical):
        _translate = QtCore.QCoreApplication.translate
        Dialog_noiseband_vertical.setWindowTitle(_translate("Dialog_noiseband_vertical", "Vertical Noise Bands"))
        self.label.setText(_translate("Dialog_noiseband_vertical", "Width (px)"))
        self.label_2.setText(_translate("Dialog_noiseband_vertical", "Period (px)"))
        self.label_3.setText(_translate("Dialog_noiseband_vertical", "Magnitude"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_noiseband_vertical = QtWidgets.QDialog()
    ui = Ui_Dialog_noiseband_vertical()
    ui.setupUi(Dialog_noiseband_vertical)
    Dialog_noiseband_vertical.show()
    sys.exit(app.exec_())
